/*
 * NFT Storage API
 *
 * # API Reference 
 *
 * API version: 1.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package nftstorage

import (
	"encoding/json"
)

// UnauthorizedErrorResponseError struct for UnauthorizedErrorResponseError
type UnauthorizedErrorResponseError struct {
	Name *string `json:"name,omitempty"`
	Message *string `json:"message,omitempty"`
}

// NewUnauthorizedErrorResponseError instantiates a new UnauthorizedErrorResponseError object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUnauthorizedErrorResponseError() *UnauthorizedErrorResponseError {
	this := UnauthorizedErrorResponseError{}
	var name string = "HTTP Error"
	this.Name = &name
	var message string = "Unauthorized"
	this.Message = &message
	return &this
}

// NewUnauthorizedErrorResponseErrorWithDefaults instantiates a new UnauthorizedErrorResponseError object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUnauthorizedErrorResponseErrorWithDefaults() *UnauthorizedErrorResponseError {
	this := UnauthorizedErrorResponseError{}
	var name string = "HTTP Error"
	this.Name = &name
	var message string = "Unauthorized"
	this.Message = &message
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *UnauthorizedErrorResponseError) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UnauthorizedErrorResponseError) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *UnauthorizedErrorResponseError) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *UnauthorizedErrorResponseError) SetName(v string) {
	o.Name = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *UnauthorizedErrorResponseError) GetMessage() string {
	if o == nil || o.Message == nil {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UnauthorizedErrorResponseError) GetMessageOk() (*string, bool) {
	if o == nil || o.Message == nil {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *UnauthorizedErrorResponseError) HasMessage() bool {
	if o != nil && o.Message != nil {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *UnauthorizedErrorResponseError) SetMessage(v string) {
	o.Message = &v
}

func (o UnauthorizedErrorResponseError) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	if o.Message != nil {
		toSerialize["message"] = o.Message
	}
	return json.Marshal(toSerialize)
}

type NullableUnauthorizedErrorResponseError struct {
	value *UnauthorizedErrorResponseError
	isSet bool
}

func (v NullableUnauthorizedErrorResponseError) Get() *UnauthorizedErrorResponseError {
	return v.value
}

func (v *NullableUnauthorizedErrorResponseError) Set(val *UnauthorizedErrorResponseError) {
	v.value = val
	v.isSet = true
}

func (v NullableUnauthorizedErrorResponseError) IsSet() bool {
	return v.isSet
}

func (v *NullableUnauthorizedErrorResponseError) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUnauthorizedErrorResponseError(val *UnauthorizedErrorResponseError) *NullableUnauthorizedErrorResponseError {
	return &NullableUnauthorizedErrorResponseError{value: val, isSet: true}
}

func (v NullableUnauthorizedErrorResponseError) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUnauthorizedErrorResponseError) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


